name: PHPStan (php-actions)

on:
  workflow_run:
    workflows: [ "Set Up Env" ]
  push:
    branches:
      - 'develop'
      - 'feature/**'

jobs:
  phpstan-check-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/phpstan@v3
        with:
          path: src/
          arguments: 'src/ --level=5'
